title: Posts
description: A collection of documents worth sharing
url: "https://aitrmna.github.io"
baseurl: "/posts"

# Collections
collections:
  documents:
    output: true
    permalink: /:name

# Build settings
markdown: kramdown
highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
      type: "documents"
    values:
      layout: "document"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
